run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - dogsled
    - dupl
    - errorlint
    - exhaustive
    - copyloopvar
    - goconst
    - gocritic
    - godot
    - goprintffuncname
    - gosec
    - nakedret
    - nilerr
    - nlreturn
    - noctx
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - thelper
    - tparallel
    - whitespace
    - wrapcheck

linters-settings:
  govet:
    enable-all: true
  gofmt:
    simplify: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  gosec:
    excludes:
      - G304 # File path from variable (we need this for file loading)
  dupl:
    threshold: 150
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  exhaustive:
    default-signifies-exhaustive: true
  nakedret:
    max-func-lines: 30
  nlreturn:
    block-size: 2
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude some linters from test files
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - wrapcheck
        - goconst
    # Exclude doc.go from some linters
    - path: doc\.go
      linters:
        - godot
